name: ESP8266

on: [push, pull_request]

env:
  ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: http://arduino.esp8266.com/stable/package_esp8266com_index.json

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install platform
        run:  |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile Sketch
        run: arduino-cli compile --fqbn esp8266:esp8266:d1_mini rules.ino -v

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rules.ino.bin
          path: C:\\Users\\runneradmin\\AppData\\Local\\Temp\\arduino\\sketch-*/*.ino.bin
